### PR TITLE
Add command line and multiple-choice tools.

### PR DESCRIPTION
**Pull request by ericnorway**
No changes to existing code. Just added some files used for testing answers to multiple choice questions and for running command line tests. This is my first pull request, so hopefully I did this correctly :)

### CODE REVIEW

**Comment by ericnorway** [comment]
Good idea.

**Comment by meling** [comment]
@tormoder should he revise his pull request, or send a new one. How does it work?

**Comment by tormoder** [comment]
I think he could just push to his `master` and the commit will be added. Since the PR is from `ericnorway:master`.

**Comment by ericnorway** [comment]
I pushed doc.go to my master branch. It looks like it is visible from the pull request.

**Pull request merged**
